# Generated by Django 5.0.3 on 2024-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('password_again', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
