# Generated by Django 5.0.3 on 2024-03-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_newuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=120, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
